// Code generated by MockGen. DO NOT EDIT.
// Source: fsm.go
//
// Generated by this command:
//
//	mockgen -source fsm.go -destination mocks/mock_fsm.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	entity "cms/internal/entity"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFSMRepository is a mock of FSMRepository interface.
type MockFSMRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFSMRepositoryMockRecorder
	isgomock struct{}
}

// MockFSMRepositoryMockRecorder is the mock recorder for MockFSMRepository.
type MockFSMRepositoryMockRecorder struct {
	mock *MockFSMRepository
}

// NewMockFSMRepository creates a new mock instance.
func NewMockFSMRepository(ctrl *gomock.Controller) *MockFSMRepository {
	mock := &MockFSMRepository{ctrl: ctrl}
	mock.recorder = &MockFSMRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFSMRepository) EXPECT() *MockFSMRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockFSMRepository) Delete(ID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockFSMRepositoryMockRecorder) Delete(ID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockFSMRepository)(nil).Delete), ID)
}

// Get mocks base method.
func (m *MockFSMRepository) Get(ID int64) (entity.State, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ID)
	ret0, _ := ret[0].(entity.State)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockFSMRepositoryMockRecorder) Get(ID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockFSMRepository)(nil).Get), ID)
}

// GetName mocks base method.
func (m *MockFSMRepository) GetName(ID int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetName", ID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetName indicates an expected call of GetName.
func (mr *MockFSMRepositoryMockRecorder) GetName(ID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetName", reflect.TypeOf((*MockFSMRepository)(nil).GetName), ID)
}

// GetWeight mocks base method.
func (m *MockFSMRepository) GetWeight(ID int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWeight", ID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWeight indicates an expected call of GetWeight.
func (mr *MockFSMRepositoryMockRecorder) GetWeight(ID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWeight", reflect.TypeOf((*MockFSMRepository)(nil).GetWeight), ID)
}

// Set mocks base method.
func (m *MockFSMRepository) Set(ID int64, State entity.State) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ID, State)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockFSMRepositoryMockRecorder) Set(ID, State any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockFSMRepository)(nil).Set), ID, State)
}

// SetName mocks base method.
func (m *MockFSMRepository) SetName(ID int64, Name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetName", ID, Name)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetName indicates an expected call of SetName.
func (mr *MockFSMRepositoryMockRecorder) SetName(ID, Name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetName", reflect.TypeOf((*MockFSMRepository)(nil).SetName), ID, Name)
}

// SetWeight mocks base method.
func (m *MockFSMRepository) SetWeight(ID int64, Weight int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetWeight", ID, Weight)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetWeight indicates an expected call of SetWeight.
func (mr *MockFSMRepositoryMockRecorder) SetWeight(ID, Weight any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetWeight", reflect.TypeOf((*MockFSMRepository)(nil).SetWeight), ID, Weight)
}
